print('Введите число')
a = int(input())
print('Введите число еще раз')
b = int(input())
print('Выберите операцию,+,-,*,/')
c = input()
if c == '+': print(a+b)
elif c == '-': print(a-b)
elif c == '*': print(a*b)
elif c == '/': print(a/b)
else:print('Не верная операция')